apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./k8s/client-deployment.yaml
    - ./k8s/server-deployment.yaml
    - ./k8s/worker-deployment.yaml
    - ./k8s/client-cluster-ip-service.yaml
    - ./k8s/server-cluster-ip-service.yaml
build:
  local:
    push: false
  artifacts:
    - image: skrlivoj/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: skrlivoj/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: skrlivoj/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
