apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: skrlivoj/multi-client
          ports:
            - containerPort: 3000
          # following is added by VSCode Exteension Kubernetes
          # if missing, this Deployment could starve other resources
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
